name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: DNSControl create-domains
        uses: koenrh/dnscontrol-action@v3
        env:
          POWERDNS_URL: ${{ secrets.POWERDNS_URL }}
          POWERDNS_KEY: ${{ secrets.POWERDNS_KEY }}
        with:
          args: create-domains
      - name: DNSControl push
        uses: koenrh/dnscontrol-action@v3
        env:
          POWERDNS_URL: ${{ secrets.POWERDNS_URL }}
          POWERDNS_KEY: ${{ secrets.POWERDNS_KEY }}
        with:
          args: push
